name: Build PDFs

on:
  push:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    branches: ["main"]
    
permissions:
  contents: write
    
jobs:
  pdf:
    runs-on: ubuntu-latest
    container: pandoc/latex:latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup the container
        run: |
          apk add --no-cache make fontconfig font-noto ghostscript
        
      - name: Build PDFs
        run: make pdf

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-guides
          path: |
            guide_fr.pdf
            guide_en.pdf
          retention-days: 30

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            guide_fr.pdf
            guide_en.pdf
          generate_release_notes: true
